services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=webscrappingdb
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: PSQL@9H#sqXG$6PMHPJW
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - postgres
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  db:
  pgadmin:
